// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SZReport.Models;

namespace SZReport.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("SZReport.Models.SHA", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Closing")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FrontOpening")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Highest")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Lowest")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Opening")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Turnover")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UpDown")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UpDownWidth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SHAs");
                });
#pragma warning restore 612, 618
        }
    }
}
